name: Deploy Spring Boot App to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Build with Maven
      run: mvn clean package -DskipTests

    - name: Transfer WAR file to EC2
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "target/your-app.war"
        target: "~/tomcat/webapps/"

    - name: Restart Tomcat
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          ~/tomcat/bin/shutdown.sh || true
          sleep 5
          rm -rf ~/tomcat/webapps/your-app  # 기존 폴더 삭제
          ~/tomcat/bin/startup.sh
